bookticket/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('ticketsystem.urls')),
    path('pdf/',include('pdf.urls')),
    path('admin/', admin.site.urls),
]

pdf/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    #path('',views.ViewPDF.as_view(),name='pdf_view'),
    path('<str:pk>/',views.viewpdf,name='pdf_view'),
]

ticketsystem/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('',views.home,name='home'),

# VEHICLE SEGMENT
    path('vehicles/',views.vehicles,name='vehicles'),
    path('addVehicle/',views.addVehicle,name='addVehicle'),
    path('updateVehicle/<str:pk>/',views.updateVehicle,name='updateVehicle'),
    path('viewvehicle/<str:pk>/',views.viewvehicle,name='viewvehicle'),
    path('viewvehicle/<str:pk>/<str:cid>/',views.viewvehicle,name='viewvehicle'),
    path('deleteVehicle/<str:pk>/',views.deletevehicle,name='deleteVehicle'),

#VENDOR AUTHENTICATION PAGE
    path('login/',views.loginPage, name='login'),
    path('logout/',views.logoutUser, name='logout'),
    path('registration/',views.registration,name='registration'),
    path('deactivated/',views.deactivated,name='deactivated'),
    path('pending/',views.pending,name='pending'),
    path('unauthorized/',views.unauthorized),


#RESET PASSWORD SEGMENT
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name='ticketsystem/reset_password.html'),name='reset_password'),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name='ticketsystem/reset_password_sent.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='ticketsystem/reset_password_complete.html'), name='password_reset_complete'),

#VENDOR SEGMENT
    path('vendor/',views.vendorPage,name='vendor'),
    path('vendor_profile/<str:pk>/',views.user,name='vendor_profile'),
    path('update_profile/<str:pk>/',views.update_profile,name='update_profile'),
    path('uservehicle/', views.userVehicles, name='uservehicle'),


#RESERVATION SEGMENT
    path('newbooking/', views.newbooking,name='newbooking'),
    path('reservation/<str:pk>/<str:rd>/',views.reservation,name='reservation'),
    path('updatereservation/<str:pk>/<str:rid>/<str:rd>/',views.updatereservation,name='updatereservation'),
    path('reservation-list/',views.reservationList,name='reservation-list'),

#CKEDITOR FOR FILE UPLOAD USUAGE   




#ADMIN AUTHENTICATION PAGE
    path('super/',views.loginSuper, name='super'),
    path('vendorlist/',views.vendorlist,name='vendorlist'),
    path('viewcompany/<str:pk>/',views.viewCompany,name='viewcompany'),
    path('addseatplan/',views.addseatlayout, name='addseatplan'),
    path('updateseatplan/<str:pk>/',views.updateseatPlan, name='updateseatplan'),
    path('seatplan/',views.seatplanList, name='seatplan'),



]

urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticketsystem/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField



# Creating Company Name i.e. Vendor of software subscribers
class VehicleCompany(models.Model):
    ACTIVATION_STATUS=(
        ('Active','Active'),
        ('Pending','Pending'),
        ('Deactivated','Deactivated')
    )
    user_auth = models.OneToOneField(User,null=True, on_delete=models.CASCADE)
    company_name=models.CharField(max_length=100,db_index=True)
    authorizedperson=models.CharField(null=True, max_length=100, verbose_name='Authorized Person')
    address=models.CharField(max_length=200, db_index=True)
    company_info=RichTextField(blank=True, null=True)
    phone=models.CharField(max_length=20)
    account_status=models.CharField(max_length=20,choices=ACTIVATION_STATUS, default='Pending')
    companylogo=models.ImageField(null=True, blank=True, verbose_name='Company Logo')
    slug=models.SlugField(max_length=100,db_index=True, null=True)
    

    class Meta:
        ordering=('company_name',)
        verbose_name='company'
        verbose_name_plural='companies'

    def __str__(self):
        return str(self.user_auth)



# Adding Route Location for desitination name consistency
class RouteDestination(models.Model):
    destinationlocation=models.CharField(max_length=100)

    class Meta:
        ordering=('destinationlocation',)
        verbose_name='route'
        verbose_name_plural='routes'

    def __str__(self):
        return self.destinationlocation


# Adding Facility provided in the vehicle
class Facility(models.Model):
    ammenities=models.CharField(max_length=100)

    class Meta:
        ordering=('ammenities',)
        verbose_name='facility'
        verbose_name_plural='facilities'


    def __str__(self):
        return self.ammenities

class Category(models.Model):
    category=models.CharField(max_length=100)

    class Meta:
        ordering=('category',)
        verbose_name='category'
        verbose_name_plural='categories'


    def __str__(self):
        return self.category



#Seat Planning
class SeatPlan(models.Model):
    formatname=models.CharField(max_length=100, verbose_name='Name', null=True)
    seatformt=RichTextField(blank=True, null=True)
    seatlayoutimage=models.ImageField(null=True, blank=True, verbose_name='Seat Layout')

    class Meta:
        ordering=('formatname',)
    
    def __str__(self):
        return self.formatname



# Adding Vehicle of Vehicle's Company subscriber
class Vehicle(models.Model):
    vehicle_name=models.CharField(max_length=100, db_index=True, null=True)
    vehicle_number=models.CharField(max_length=20, null=True)
    facility=models.ManyToManyField(Facility)
    category=models.ForeignKey(Category, related_name='vehiclecategory', null=True, on_delete=models.SET_NULL)
    departurefrom=models.IntegerField(null=True)
    departureto=models.IntegerField(null=True)
    departuretime=models.TimeField()
    seatplan=models.ForeignKey(SeatPlan, null=True, on_delete=models.SET_NULL)
    seatcapacity=models.PositiveIntegerField(null=True)
    ticketprice=models.PositiveIntegerField()
    vehicleowner=models.ForeignKey(VehicleCompany,related_name='company', null=True, on_delete=models.SET_NULL)
    vehicle_photo=models.ImageField(null=True,blank=True)
    slug=models.SlugField(max_length=100,db_index=True, unique=True)
    boardingpointone=models.CharField(max_length=200,null=True, blank=True)
    boardingpointtwo=models.CharField(max_length=200,null=True, blank=True)
    boardingpointthree=models.CharField(max_length=200,null=True, blank=True)
    dropoffpointone=models.CharField(max_length=200,null=True, blank=True)
    dropoffpointtwo=models.CharField(max_length=200,null=True, blank=True)
    dropoffpointthree=models.CharField(max_length=200,null=True, blank=True)

    class Meta:
        ordering=('vehicle_name',)
        index_together=(('id','slug'))

    def __str__(self):
        return self.vehicle_name    



class Reservation(models.Model):
    MODE_OF_PAYMENT=(
        ('Online Payment','Online Payment'),
        ('Offline Payment','Offline Payment')
    )

    fullname=models.CharField(max_length=100, db_index=True)
    address=models.CharField(max_length=200, db_index=True)
    email=models.EmailField()
    phone=models.CharField(max_length=20)
    busid=models.ForeignKey(Vehicle,related_name='bus', null=True, on_delete=models.SET_NULL)
    busName=models.CharField(max_length=100, null=True)
    departurefrom=models.CharField(max_length=100,null=True)
    departureto=models.CharField(max_length=100, null=True)
    departuredate=models.DateField()
    departuretime=models.TimeField()
    seatnumber=models.CharField(max_length=200)
    totalprice=models.PositiveIntegerField(default=0)
    paymentmode=models.CharField(max_length=50,choices=MODE_OF_PAYMENT)

    class Meta:
        ordering=('-departuredate',)
        

    def __str__(self):
        return self.fullname
  

ticketsystem/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import VehicleCompany, Vehicle, Reservation, SeatPlan

class VehicleForm(ModelForm):
    class Meta:
        model = Vehicle
        fields = '__all__'
        #exclude=['vehicleowner']
        widgets={
            'departuretime':forms.TextInput(attrs={'placeholder':'HH:MM:SS'}),
            'boardingpointone':forms.TextInput(attrs={'required': False}),
            
        }  



class CreateVendorForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','username','email','password1','password2']


class CompanyprofileForm(ModelForm):
    companylogo = forms.ImageField(required=False)
    class Meta:
        model = VehicleCompany
        fields = ['company_name', 'authorizedperson', 'address', 'phone','companylogo', 'company_info', 'slug']
        # widgets={
        #     'company_info':TinyMCE(attrs={'class':'form-control'}),
        # }


class ReservationForm(ModelForm):
    
    class Meta:
        model = Reservation
        fields = '__all__'
        #fields = ['id','fullname','address','email','phone','busid','busName','departurefrom','departureto','departuredate','departuretime','seatnumber','totalprice','paymentmode']
        widgets={
            'departuredate':forms.TextInput(attrs={'class':'form-control','readonly':'readonly'}),
            'departuretime':forms.TextInput(attrs={'class':'form-control','readonly':'readonly'}),
            'seatnumber':forms.TextInput(attrs={'class':'form-control','readonly':'readonly'}),
            'totalprice':forms.TextInput(attrs={'class':'form-control','readonly':'readonly'}),
        }   


class SeatPlanForm(ModelForm):
    class Meta:
        model = SeatPlan
        fields = '__all__'
        
        

ticketsystem/templates/ticketsystem/add_vehicle.html
{%extends 'ticketsystem/main.html'%}
{%block content%}
<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block yellowbg"></div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Add New Vehicle</h1>
              </div>
              
              <form class="user frontend" method="POST" action="" enctype="multipart/form-data">
                {%csrf_token%}
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <label for="id_vehicle_name">Vehicle Name</label>
                    {{form.vehicle_name}}
                  </div>
                  <div class="col-sm-6">
                    <label for="id_vehicle_number">Vehicle Number</label>
                    {{form.vehicle_number}}
                  </div>
                </div>
                <div class="form-group">
                  <label for="id_slug">Slug</label>
                  {{form.slug}}
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <label for="id_ticketprice">Ticket Price</label>
                    {{form.ticketprice}}
                  </div>
                  <div class="col-sm-6">
                    <label for="id_departuretime">Departure Time</label>
                    {{form.departuretime}}
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <label for="id_vehicleowner">Vehicle Owner</label>
                    {{form.vehicleowner}}
                  </div>
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <label for="id_category">Category</label>
                    {{form.category}}
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-6">
                    <label for="id_departurefrom">Departure From</label>
                    <select name="departurefrom" class="form-control" required="" id="id_departurefrom">
                      <option value="" selected="">Departure From</option>
                      {%for location in route_location%}
                        <option value="{{location.id}}">{{location}}</option>
                      {%endfor%}
                    </select>
                  </div>
                  <!-- <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control-user" name="{{form.departurefrom.name}}" id="id_{{form.departurefrom.name}}" placeholder="Departure From">
                    <div class="dropdown mb-4">
                      <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButtonfrom" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Departure From
                      </button>
                      <div class="dropdown-menu animated--fade-in" aria-labelledby="dropdownMenuButtonfrom">
                        
                        {%for location in route_location%}
                        <a class="dropdown-item" href="#">{{location}}</a>
                        {%endfor%}
                      </div>
                    </div>
                  </div> -->
                  <div class="col-sm-6">
                    <label for="id_departureto">Departure To</label>
                    <select name="departureto" class="form-control" required="" id="id_departureto">
                      <option value="" selected="">Departure To</option>
                      {%for location in route_location%}
                        <option value="{{location.id}}">{{location}}</option>
                      {%endfor%}
                    </select>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-6">
                    <label for="id_facility"></label>
                    {{form.facility}}
                  </div>
                </div>
                <div class="form-group">
                  <div class="custom-file">
                    {{form.vehicle_photo}}
                    <label class="custom-file-label" for="customFile">Choose Vehicle Photo</label>
                  </div>
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <label for="id_seatplan">Seat Plan</label>
                    {{form.seatplan}}
                  </div>
                  <div class="col-sm-6">
                    <label for="id_seatcapacity">Seat Capacity</label>
                    {{form.seatcapacity}}
                  </div>
                </div>
                <hr>
                <div class="card mb-4 py-3 border-bottom-primary">
                  <div class="card-body">
                      <p>Boarding Point and Time</p>
                      <div class="form-group">
                          <label for="id_{{form.boardingpointone.name}}">First Boarding Point and Time</label>
                          {{form.boardingpointone}}
                      </div>
                      <div class="form-group">
                          <label for="id_{{form.boardingpointtwo.name}}">Second Boarding Point and Time</label>
                          {{form.boardingpointtwo}}
                      </div>
                      <div class="form-group">
                          <label for="id_{{form.boardingpointthree.name}}">Third Boarding Point and Time</label>
                          {{form.boardingpointthree}}
                      </div>
                    
                      
                  </div>
              </div>
              
             
              <div class="card mb-4 py-3 border-bottom-primary">
                  <div class="card-body">
                      <p>Dropoff Zone and Time</p>
                      
                      <div class="form-group">
                          <label for="id_{{form.dropoffpointone.name}}">First Dropoff Point and Time</label>
                          {{form.dropoffpointone}}
                      </div>
                      <div class="form-group">
                          <label for="id_{{form.dropoffpointtwo.name}}">Second Dropoff Point and Time</label>
                          {{form.dropoffpointtwo}}
                      </div>
                      <div class="form-group">
                          <label for="id_{{form.dropoffpointthree.name}}">Three Dropoff Point and Time</label>
                          {{form.dropoffpointthree}}
                      </div>
                  </div>
                </div>
                <button type="submit" class="btn btn-primary btn-user btn-block">Add Vehicle</button>
              </form>
              {{form.errors}}
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
{%endblock%}

ticketsystem/templates/ticketsystem/auth.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Book My Ticket - Login</title>

  <!-- Custom fonts for this template-->
  <link href="{%static 'vendor/fontawesome-free/css/all.min.css'%}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{%static 'css/sb-admin-2.css'%}" rel="stylesheet">
  <link href="{%static 'css/main.css'%}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            {%block content%}
            {%endblock%}
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{%static 'vendor/jquery/jquery.min.js'%}"></script>
  <script src="{%static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{%static 'vendor/jquery-easing/jquery.easing.min.js'%}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{%static 'js/sb-admin-2.min.js'%}"></script>

</body>

</html>

ticketsystem/templates/ticketsystem/pending.html
{% extends 'ticketsystem/auth.html' %}
{% block content %}
<div class="row">
    <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
    <div class="col-lg-6">
      <div class="p-5">
        <div class="text-center">
          <h1 class="h4 text-gray-900 mb-4">Account Activation Pending</h1>
        </div>
        <p>Your account is currently under <b>Pending Status</b>.</p>
        <p>To get full access to this software, please call our support at <a href="tel:9841331423">9841331423</a> or email us at <a href="mailto:support@wisherstech.com">support@wisherstech.com</a></p>
        <hr>
        <div class="text-center">
          <a class="small btn btn-primary" href="forgot-password.html">View Package Plan</a>
        </div>
        <div class="text-center">
          <a class="small" href="register.html">Terms and Conditions</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

ticketsystem/templates/ticketsystem/reservation.html
{% extends 'ticketsystem/vendorLoggedIn.html' %}
{% block content %}
<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-gray-600">
            <div class="reser">
            {% for seatbook in seat_booked %}
            {{seatbook.seatnumber}}
            {% endfor %}
          </div>
            <input type="hidden" name="tp" id="tp" value="{{vehicle_id.ticketprice}}">
            {{seats.seatformt | safe}}
            
          </div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Book a Ticket</h1>
              </div>
              <form class="user frontend" method="POST" action="">
                  {% csrf_token %}
                <div class="form-group">
                    <label for="{{form.fullname.id_for_label}}">Full Name</label>
                    {{form.fullname}}
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                      <label for="{{form.address.id_for_label}}">Address</label>
                    {{form.address}}
                  </div>
                  <div class="col-sm-6">
                    <label for="{{form.phone.id_for_label}}">Phone</label>
                    {{form.phone}}
                  </div>
                </div>
                <div class="form-group">
                  <label for="{{form.email.id_for_label}}">Email</label>
                  {{form.email}}
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <label for="{{form.departurefrom.id_for_label}}">Departure From</label>
                    {% for location in route_location %}
                    {% if location.id == form.departurefrom.value %}
                    <input type="text" name="departurefrom" maxlength="100" readonly required_id="id_departurefrom" value="{{location.destinationlocation}}">
                    {% endif %}
                    {% endfor %}
                    
                  </div>
                  <div class="col-sm-6">
                    <label for="{{form.departureto.id_for_label}}">Departure To</label>
                    {% for location in route_location %}
                    {% if location.id == form.departureto.value %}
                    <input type="text" name="departureto" maxlength="100" readonly required_id="id_departureto" value="{{location.destinationlocation}}">
                    {% endif %}
                    {% endfor %}
                    
                  </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                      <label for="{{form.departuredate.id_for_label}}">Departure Date</label>
                      <input type="text" name="departuredate" readonly value="{{rd}}">
                    </div>
                    <div class="col-sm-6">
                      <label for="{{form.departuretime.id_for_label}}">Departure Time</label>
                      {{form.departuretime}}
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                      <label for="{{form.seatnumber.id_for_label}}">Seat Number</label>
                      {{form.seatnumber}}
                    </div>
                    <div class="col-sm-6">
                      <label for="{{form.totalprice.id_for_label}}">Total Price</label>
                      <input type="number" name="totalprice" id="id_totalprice" value="0" min="0" required="" id="id_totalprice">
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                      <label for="{{form.busid.id_for_label}}">Bus ID</label>
                      <input type="hidden" name="busid" readonly required_id="id_busid" value="{{vehicle_id.id}}">
                      <input type="text" name="busName" readonly id="id_busName" value="{{vehicle_id.vehicle_name}}">
                    </div>
                    <div class="col-sm-6 mb-3 mb-sm-0">
                      <label for="{{form.paymentmode.id_for_label}}">Payment Mode</label>
                      {{form.paymentmode}}
                    </div>
                    
                  </div>

                <button type="submit" class="btn btn-primary btn-user btn-block">Book Ticket</button>
                
              </form>
              {{form.errors}}
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
{% endblock %}

ticketsystem/templates/ticketsystem/reset_password.html
{%extends 'ticketsystem/auth.html'%}
{%block content%}
<div class="row">
    <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
    <div class="col-lg-6">
      <div class="p-5">
        <div class="text-center">
          <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
          <p class="mb-4">We get it, stuff happens. Just enter your email address below and we'll send you a link to reset your password!</p>
        </div>
        <form class="user frontend" method="POST">
          {%csrf_token%}
          <div class="form-group">
            <input type="email" name="email" autocomplete="email" maxlength="254" required="" id="id_email" class="form-control form-control-user" placeholder="Enter Email Address...">
          </div>
          <button class="btn btn-primary btn-user btn-block">Reset Password</button>
        </form>
        <hr>
        <div class="text-center">
          <a class="small" href="/registration/">Create an Account!</a>
        </div>
        <div class="text-center">
          <a class="small" href="/login/">Already have an account? Login!</a>
        </div>
      </div>
    </div>
  </div>
{%endblock%}

ticketsystem/templates/ticketsystem/updatereservation.html
{% extends 'ticketsystem/vendorLoggedIn.html' %}
{% block content %}
<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-gray-600">
            <div class="reser">
            {% for seatbook in seat_booked %}
            {{seatbook.seatnumber}}
            {% endfor %}
          </div>
            <input type="hidden" name="tp" id="tp" value="{{vehicle_id.ticketprice}}">
            {{seats.seatformt | safe}}
            
          </div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Update Ticket Reservation</h1>
              </div>
              <form class="user frontend" method="POST" action="">
                  {% csrf_token %}
                <div class="form-group">
                    <label for="{{form.fullname.id_for_label}}">Full Name</label>
                    {{form.fullname}}
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                      <label for="{{form.address.id_for_label}}">Address</label>
                    {{form.address}}
                  </div>
                  <div class="col-sm-6">
                    <label for="{{form.phone.id_for_label}}">Phone</label>
                    {{form.phone}}
                  </div>
                </div>
                <div class="form-group">
                  <label for="{{form.email.id_for_label}}">Email</label>
                  {{form.email}}
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <label for="{{form.departurefrom.id_for_label}}">Departure From</label>
                    <input type="text" name="departurefrom" maxlength="100" readonly required_id="id_departurefrom" value="{{form.departurefrom.value}}">
                    
                  </div>
                  <div class="col-sm-6">
                    <label for="{{form.departureto.id_for_label}}">Departure To</label>
                    <input type="text" name="departureto" maxlength="100" readonly required_id="id_departureto" value="{{form.departureto.value}}">
                    
                  </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                      <label for="{{form.departuredate.id_for_label}}">Departure Date</label>
                      <input type="text" name="departuredate" readonly value="{{rd}}">
                    </div>
                    <div class="col-sm-6">
                      <label for="{{form.departuretime.id_for_label}}">Departure Time</label>
                      {{form.departuretime}}
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0 updateseat">
                      <label for="{{form.seatnumber.id_for_label}}">Seat Number</label>
                      <input type="text" name="seatnumber" id="id_seatnumber" data-value="{{form.seatnumber.value}}" required="">
                    </div>
                    <div class="col-sm-6">
                      <label for="{{form.totalprice.id_for_label}}">Total Price</label>
                      <input type="number" name="totalprice" id="id_totalprice" value="{{form.totalprice.value}}" min="0" required="">
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                      <label for="{{form.busid.id_for_label}}">Bus ID</label>
                      <input type="hidden" name="busid" readonly required_id="id_busid" value="{{vehicle_id.id}}">
                      <input type="text" name="busName" readonly id="id_busName" value="{{vehicle_id.vehicle_name}}">
                    </div>
                    <div class="col-sm-6 mb-3 mb-sm-0">
                      <label for="{{form.paymentmode.id_for_label}}">Payment Mode</label>
                      {{form.paymentmode}}
                    </div>
                    
                  </div>

                <button type="submit" class="btn btn-primary btn-user btn-block">Update Reservation</button>
                
              </form>
              {{form.errors}}
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
{% endblock %}